Move wrapper definition to option default
This needed to make it work with `flake-parts`, otherwise we get:

    error: The option `build.wrapper' is defined multiple times.